= Against the Maze

This is the main line plot of Episode 1. The player arrives in the Second Realm with little idea of what lies ahead but with one clear goal - progressing past it into the Third Realm.

There is initially little information on the Second Realm. The party explores and discovers the inhabited Domains: Ichiba, Danaos and Aenen. Most tell the party not to bother escaping, for beyond lies only wilderness. The party learns that the wilderness areas are haunted by seven deadly spirits, who must be defeated by any seeking to escape the Realm.

To travel beyond the inhabited areas, the player gains access to either the Leonal castle Danaos and thence to Stygios Forest, or the gnome city of Aenen and thence to Tornado Mountain.

Travelling up Tornado Mountain, the party is confronted by Saropon the Vile, one of the demonic minions of Usark. He warns the party that they have come to the attention of the forces that watch over the Maze, and that they should not proceed.

Travelling in the darkness of Stygios Forest, the party is confronted by Nusor the Torturer, one of the demonic minions of Usark. He warns the party that they have come to the attention of the forces that watch over the Maze, and that they should not proceed.

Heedless of these warnings, the party explores the wilderness and defeats the seven deadly spirits therein: the gnoll demon Ineoth-Em-Risiss-Mar in the dark Stygios Forest, the dragon Igor in the ruins of Hail, the unliving Ghul in the Plain of Pillars, the mad sorcerer Bel Ies in his hut the Writhing Mire, the ninja mantis Yenlou in the labyrinth Hianbian, and the hag sisters Getsel Gnawtooth and Miriam Marrowsucker in the Caves of Ilast.

Emerging from the Caves of Ilast, the party tarries momentarily on the idyllic Isle of the Gate. Descending below the isle, they make use of the seven items collected from the defeated deadly spirits to solve the puzzles in Ekirths tomb and proceed to the Temple of the Gate.

The demon Nhapukom Banesoul, one of the minions of Usark, awaits the party before the Great Gate. He warns the party that Usark himself will move against them should they proceed to the Third Realm, and that there is still time for them to go back. If they proceed, he attacks without mercy.

Defeating Nhapukom, the party step through the Gate and exit the Second Realm.