= The Tale of Azael

A mysterious man called just "Azael the Half-Blind" or known as "The Escaped One" centuries ago is the said to have escaped from the Maze. The tales goes that Azael escaped the First Realm centuries ago, but traded his left eye to do so. He then wandered through this Second Realm for years as a poet until one day he announced that he would escape this Realm too. Some say he had to trade his second eye to escape this Realm, but either way, he one day disappeared. This was shortly before Hail was razed to the ground by the Maze, thus many think that this was simply retaliation to his escape. Azael the Half-blind's clues are everywhere, as well his image subtly permeate society with expressions like "Azael would!" meaning that an impossible task is possible and "To Azael" as a celebratory toast or using the 'half-blind' as colour (e.g. "I'd give my left eye for that!" or "Why should I trust your word? You still have both your eyes!").


Flavour related to Azael:

In the Gatehouse intro dungeon a message is carved on a wall "A journey of a thousand miles begins with a single step. - Azael the Half-blind."

_Outside Danaos Castle is an old weather-beaten signpost that reads "True vision needs but one eye." in reference to The Eye of Azael._

_Somewhere on the streets of Ichiba the players are stopped by a beggar who offers to sell them the "Mug of Azael". He promises that it is the real mug that Azael drank from the Fountain of Youth from and all who drink from live long lives. It is a fake artefact, but this provides an opportunity for the players to be told the story of Azael the Half-blind._

_The party finds a shallow grave in Stygios Forest. It is old and just a skeleton is there, but a small, silver ornate dagger is found. The dagger has the words "Whatever the cost. - Azael" carved into it._

_To the north of Tornado Mountain, a cave that smells musty and dry, and is heaped with bones of all descriptions. It appears deserted at first glance. It was once occupied by a dragon. Some text has been crudely carved into the wall: "Azael here Slew the dragon Brontes, single handed. Think of me as ye Pass by traveller, and look for me Beyond the Gate."_

_A book in the library of Hail tells the tale of Azael the Half-blind setting out on his final quest to escape the Second Realm._

_In the Plain of Pillars, there is a small, long-since-dried oasis that the characters can stumble onto. If the characters look around they can find that the following message by Azael is carved as a warning into a small cracked pillar near the dried oasis: "Drink not the water, for it is poisoned. Rest in peace, friend. - Azael." If the party searches this spot again, they dig up a shallow grave white gleaming white skeleton in it. Nothing else is here._

== The Eye of Azael

_"The Eye of Azael" is a rumoured artefact that surfaced a century or so ago. There are two conflicting stories about it. The first says that it is the left eye of Azael that finally followed him out of the First Realm and that all that wear it can see the path to escaping the Maze. The second says that the artefact is Azael's right eye that he traded to escape this Second Realm and that all those that touch it are cursed to fall afoul of the Maze and its Guardians. Whichever story is correct, the fact is that the gruesome relic has a history steeped in blood, back stabbings and mystery and that for anyone to wear it, they have to carve out their own eye. No one currently knows where The Eye of Azael is, but rumours abound..._

Flavour related to the Eye

_Someone in Danaos Castle discusses legends about The Eye of Azael, if the players bribe him a few coins. In that case, he explains to the players that he believes The Eye of Azael is in Hail, but cautions them as he has come to the conclusion that it is cursed and one should avoid it._

_One of the items discovered in Benne O'Corren's chest in Ichiba is a stolen parchment correspondence from within the White Order: "The Eye has surfaced. The Hidden Witch of Hail suspected owner. End. Drackurus of the White Order."_

_Stentor in Danaos Village becomes quite talkative and goes in the legend of Azael and his eye. He talks of positive tale of The Eye of Azael as the ultimate weapon._

_If the players search the tomb of the dragon after defeating him, they find The Eye of Azael. It is a vile-looking single green eye that shifts on the spot to always look at you. The moment the players find it, it attaches itself to whichever character is carrying Azael's silver dagger (that may have been found in Stygios forest) and explains (i.e. via its description) that if its bearer wields the silver dagger of Azael in combat, they shall be protected. Basically, the silver dagger is just a fairly useless dagger, except when fighting against guardians of the Maze, when it gets tons and tons of bonuses. The Eye of Azael also has a deteriorating effect on its bearer, where their strength and hit points drop a bit when bearing it._