= Castle Fangorn

You survey the blasted and inhospitable landscape. Shattered and tumbled rocks cover the ground and are piled up in impassable heaps around the level space that you are in. Tattered grey clouds race across an empty sky, driven by a freezing wind that moans relentlessly from the west. You shudder and draw your clothing closer around you. To your right looms an evil looking castle, rough cut stone walls and battlements menacing the stormy sky, dark window slits peering vacantly at you like the eyes of a skull. Human skeletons litter the stony ground around it.

You enter. The castle hall receeds into darkness. Flickering torches shed little light and less heat. The cold inside the castle momentarily makes you gasp. The temperature is well below freezing, to be sure. But something else about this place makes your gut clench and chills you to the bone, something unnatural and terrifying that seems to be flickering just at the edge of your vision and the back of your mind. You wonder if exploring here is such a good idea...

Castle Fangorn is the secret Domain of black magic. All other magic colours are suppressed here.

After slaying the vampire Rhys, who was the secret leader of the Ichiba Chamber of Commerce, they party discover among his possessions a small vial of disgusting black blood.

Travelling to the ruins of Hail, the party approaches one of the inert pillars in the courtyard of Gates and pours the black blood at the base. The pillar comes to life - henceforce it is a Gate to Castle Fangorn.

The castle is a dark and terrifying place. Undead roam the halls, attacking the party in merciless waves. Eventually fighting their way to the windswept roof top, the party discover two crypts. One contains the skeleton of a man, long dead, whose name may have been Eokil. The party enters the other and finds it seemingly empty, but only for a moment. The vampire lord of the castle reveals himself. Fangorn broods in his castle, cold and alone. He scornfully thanks the party for relieving his boredom, the attacks, wielding a large iron spike. He is a dangerous opponent, but eventually the party triumph.