= Dalen

Exploring the ruins of Hail, the party do battle with a clump of colonising omnifids. When slain, the living plants drop strange seeds - taflen seeds. Taking the seeds back to Ichiba, the party brings them to the magical garden of the gnome Glaucus and plants them there. In a flash they are transported to the secret Domain of Dalen.

You appear in a lush jungle, an amazing profusion of growth surrounds you and vegetation smells fill your nostrils. The air is warm and humid. Giant trees tower far overhead, their trunks vanishing into the greenish gloom beneath their mighty canopies. Vines and creepers hang low overhead. The place is oddly quiet... few of the animal sounds that you would expect in a place like this are to be heard...

Dalen is the verdant forest Domain of green magic. All other colours of magic are suppressed.

The Domain is guarded by the brothers Ren San and Tao, samurai cat warriors. The two watch the party as they move across Dalen, and both appear before the adventurers warning them to turn back.

The party ignores the warnings and forges ahead, slaying the plant and animal life that stands in their way. Eventually the brothers make a stand in a clearing near their wicker huts. They are both formidable opponents. Battle rages in the clearing, and the brothers are slain defending their homes. The party takes what little treasure they have and eventually leaves Dalen.