= Disciples of The Lady

This plot line deals with the Leonals in Danaos Castle and their battle against the Gnomes of Aenen.

The Leonals are a tall lion headed warrior race. Their White Order of knights rides from Danaos Castle and brings the just and fair rule of The Lady through much of the lands of the Second Realm. The see themselves as the protectors of the gnomes and Ichiba against the dangers of the wilderness realms beyond their castle. They conflict with the gnomes over the latters refusal to submit to this rule.

While exploring Ichiba City, the party speaks to Diomedes, the leonal keeper of the shrine to The Lady in the city. When pressed for quests, he tells them that some incense has been stolen and he would appreciate it's return.

Exploring the north side of town, the party discover the incense in a chest in one of the thieves guild safe houses. Returning it to Diomedes, they are warmly thanked. Diomedes tells them to speak his name to the doorwarden of Danaos castle, who will grant them entry.

Leaving the city and travelling north along the Ichiba road, the party pass through the Gate and arrive in the hamlet outside the walls of Danaos castle. Initially they are denied entry to the castle by the doorwarden Stenelaus, but on the reputation of Diomedes he lets them pass within.

The castle is built atop a Gate to Stygios forest, but the way to the dungeons is sealed. The party seeks out the leonal general Belisarius in his war room. Belisarius, correctly guessing that they seek entrance to the dungeons, sees a way to solve two problems at once. A fierce wyrm has invaded the chambers below from through the gate. He grants that party access to the dungeons, on condition that they slay the intruder.

Descending to the dungeons below Danaos castle, the party finds and slays the large wyrm in the chamber of the Gate. They pass through the Gate and arrive in Stygios forest.

_todo: war with the gnomes_