= On a Granite Throne

This plot line deals with the Gnomes in the underground city Aenen and their battle against the Leonals of Danaos.

The gnomes build complex automata to serve them, and are masters of elemental magic. They are small of stature but are strong magic users and stealthy within the forests of their home. They seek to delve deeper within the earth, to better understand the workings of machine and the the elements. They conflict with the White Order over their refusal to submit to the rule of The Lady's law.

While exploring the forests in the south of Ichiba Domain, the party comes across the skeleton of a gnome scout. From the remains, they retrieve a gold ring bearing the name Antenor.

Travelling further south, the party arrive outside the entrance to Aenen, but are initially denied entry by the Gatekeeper Ideaus. However on presenting the ring of Antenor, they are allowed inside to report what they have discovered to Kin Mnesus.

Descending into the underground city of Aenen, the party makes their way to Mnesus' gloomy throne room. He is grieved to learn of Antenor's death, and grudgingly grants the party the freedom of the city. Correctly guessing that they seek access to the wilderness realms, he tells them that the gnomes had uncovered a Gate to Tornado Mountain in their delvings. He has but one task for them - to hunt down and slay a rogue automata digging machine that has escaped to the surface and is roaming the forest.

Tracking down and slaying the clockwork digger, the party return with the head to Mnesus. He grants them access to the cave containing the Gate, and the party pass through to the peak of Tornado Mountain.

_todo: war with the leonals_