= Other Wayfarers

_Six other adventurers roam the Second Realm, also seeking escape._

== Rainmaker
Human Male, Gadgeteer/Sorcerer

_The winding paths of the Second Realm are trod by the tall, gaunt figure of Rainmaker. Older then he looks, passers by first note his close cropped white hair and unshaven chin, framing his faintly mocking sneer. They then take in the slim fitting patchwork coat, somewhat ragged, that swirls around his booted calves, and seeking out his eyes are defeated by the tint of a pair of scorched and dented goggles. Seeking weapons they see little save for an unwieldy looking arbalest strapped to his broad shoulders, a matching quiver of iron bolts taps against his thigh. Perhaps by now they have thought to utter a greeting, but it falls on empty space as Rainmaker's long strides carry him past the stricken onlooker and onwards down the path. Potent in magic and in mechanics, Rainmaker seldom stops to talk to the natives._

== Eva Wingfield
Triton Female, Amazon

== Gurney
Dwarf Male, Skald

== Red Greave
Elf Male, Hero

A popular hero, the subject of many pulp fiction novels in Ichiba

== Lorelei
Human Female, Druid
----
"You are surrounded by a sense of peace as you enter the sanctuary. Pleasant greenery of all sorts fills the room, and the air smells sweet and fresh. All slender robed woman appears from amongst the foliage and gracefully approaches you. This is a druidic sanctuary if ever you've seen one, albeit a small and secretive one. Your inclination is to treat the guardian who approaches with respect and honesty."
----

Lorelei keeps a secret sanctuary outside the walls of Danaos Castle.

XXXX
???
