= Our Last Hope

_The M没k are a technologically advanced spacefaring race. Big fuzzy buggers, basically a knock off of the Wizardry Mook race, which in turn are a knock off of the Star Wars Wookies._

_Years ago, the six crew members of the MTV Iyala (Militarised Transport Vessel) experienced catastrophic technical difficulties and were forced to crash land on a small planet orbitting a backwater star near their location. They found themselves in the Second Realm of the Maze._

_The Iyala carried a cargo that included over a million frozen zygotes and germ plasm. Shortly after planetfall, primary power went offline and life support capability was substantially diminished. Faced with their inability to refrigerate the zygotes, the crew decided to activate as many as could be incubated by the crippled systems of the craft. A year later, just over a hundred young M没k were born._

_The survivors activated the rescue beacon and built a small settlement near the dead hulk of the Iyala. They were lucky in that the Maze was slow in taking notice of them, and the automated defences of the ship were used to fight off the first few years of incursions._

_Rescue has not come. Secondary power has failed and the Iyala can no longer power the rescue beacon or any of the other primary systems. The first generation of M没k young have spawned a second generation, and the small settlement is in escalating battle against incursions from the Maze. As the technology and supplies dwindle and they are forced to fight constantly for survival, the younger generation has regressed. They know of the spacefaring days only as tales passed down across generations, and skills to work the remaining technology of the Iyala are discarded in favour of the crafting of low-tech weapons with which to battle the Maze. They have began taking barbaric names out of the past history of the M没k._

_Today, only one of the original crew members still lives: Ookla, called The Oldest by the others. He stays in his hut near the Iyala, and is respected but not followed by the youngers. He is frail but still sharp, and has not given up hope of rescue arriving, or of being able to activate the Iyala's last operational escape pod and using it to find help somehow. In a tranquil garden behind his hut lie the graves of the other five crew members: Mornuk, Aefla, Hurq, Aaknateg, and Qibar._

_Keteswayo, Captain of the Iyala is the leader of the settlement. He is a second generation male, a strong warrior with little time for the old tales. He seeks to aggressively expand and fortify the settlement against the Maze, and forge a life and place for his people in the Second Realm._