= Pixie Dust

_This character's true name is "Benne O'Corren" and he is a pixie trapped by the Maze._

_Down a dead end in the Gatehouse dungeon the party finds a skeleton with a silver ring, a mace and piece of parchment with the numbers "256" scrawled on it (this parchment relates to a combination of a locked door in Ichiba). Thief/Ninja/Priest can spot signs of murder. If the party has a thief and they noticed the "thieves guild claims this area", then the thief realizes that this dungeon complex doubled as a thieves guild safe house for a while, but has been abandoned for some reason._

_A hidden chest in Ichiba Domain South contains a cache of gnomish equipment and booze. The chest also contains a parchment advertising "Gnobbles Finest Tobaccos".  This is a tobaccoist in Aenen and is where the players can by "Time tobacco" for Benne O'Corren what he wants._

_Somewhere down the road to Ichiba City the party passes a strange-looking man sleeping on his back under a large tree with his hat tilted over his face. He is dressed from head to toe in yellow and blue stripped clothes. He does not take notice of the players, though if they try to talk to him, he just replies "Got Time? No... I thought not." and continues to sleep. If the players continue to bug him, he just suddenly disappears into thin air with a little puff of rose-scented smoke and a chuckle (though he always reappears and is always found in this spot when/if the players ever return).  What he is looking for is his is some rare tobacco called "Time". If the players find it and bring it to him, he sits up, flicks out an ebony pipe and lights it up with a big smile. "Aye, this be a find that makes ole' Benne O'Corren in your gratitude. So, any trade is two-ways and Benne O'Corren always keeps his side." And he winks, chuckles and disappears into thin air (for good, this time) in a cloud of rose scented smoke. The players all level-up one full level from this event. Only after this has happened, if the players search the spot where he was sleeping they find a small pot of gold tucked under the twisted roots fo the tree he was lying against._

_Exploring Ichiba City, the party finds a door with a strange lock that needs a combination of three numbers to open. The "256" parchment found is the key that opens this door._

_In Ichiba City, as the players walk past a women cooling pies off on her window they hear her loudly complaining to her husband how a man in yellow and blue stripped clothing keeps appearing and stealing them and she'll catch him one day and take his right eye as payment! It's Benne O'Corren's lunch._

_In the Storytellers Market in Aenen, the party can visit Gnobbles Finest Tobaccos. They can buy a range of very expensive and very useless items here, but included on the list is one called "Time Tobacco, for the timeless taste". This is the tobacco that Benne O'Corren is looking for._

_O'Corren keeps a room off a corridor in Hianbian. If the players have brought him the Time Weed, he welcomes them in and asks them where they want to go: Hail or Ilast? Depending on what they say, the next door they go through takes them there. If the players have not brought him the Time Weed yet, he looks up, flustered and tries to hide a big pot of gold himself him. "Aye, so-so rude, just walking straight on in on poor ole' Benne O'Corren... Begone, ye blasted pests!" he shouts at the players, flicking his hand, and they get teleported straight to a random chamber with a fight in it._