= Power Untapped

This plot line deals with the witch Imogen and her struggle for power both magical and political in Ichiba.

After a hundred years Imogen nears her hidden goal of unlocking the secret of eternal life. She secretly sees this as her way defeating the Maze. Her power stems from her magic, magical allies (golems and plants), and the Gnolls, who treat her as semi-divine. She conflicts with the CoC over their attempts to regulate her activities. She conflicts with the Thieves over their repeated attempts to rob her.

Exploring the streets of Ichiba city, the party find a mysterious door that can only be opened by using a magical spell. Inside, a chest guarded by enemies hard to beat without magic contains an amulet bearing Imogen's name. On presenting this amulet to the guardian golem at the door to her tower, the party is allowed access.

Passing up through the tower, the party find Imogen in her boudoir surrounded by living vegetation at the top of the tower. She welcomes them and asks if they are willing to perform some tasks on her behalf, as she is preparing for a ritual and cannot leave her tower at the moment.

As a first task, Imogen gives the party an ebony amulet and asks them to place it on the altar of the death god Nergal that is located in Stygios Forest. They must report back on what occurred and bring any items that appear back to her. Travelling the long road to Stygios forest, the party locate the alter in a dark glade surrounded by luminous mushrooms. Placing the amulet on the altar, it vanishes in the suddenly growing darkness and mist. An evil spirit appears and attacks the party. Defeating the apparition, they discover the Spagyric Gem lying on the altar. Returning to Ichiba, they tell Imogen what happened and give her the gem. She is surprised, having expected the amulet to remain unharmed, but happy to receive the gem. She rewards the party with magical items.

For the next task, Imogen requires the party to travel to the ruins of the library in Hail and retrieve Al-Khidr's Grimoire. Travelling to Hail, the party discovers the book near the remains of the unfortunate librarian. They return and present it to Imogen, who rewards them with magical items. After this task Imogen begins preparations for the incantation. The COC and Thieves are alarmed and both move against her.

Imogen knows that her enemies will leave her little time. She asks the party to take a message to the Gnoll village asking them to rise against the city. The party travels to the village and delivers the message. They gnolls have been preparing for this day. They invade the city. Battle rages on the streets. The Thieves and merchants mostly leave town. Imogen makes her final preparations.

Imogen gives the party one final task. She has learned that the Chamber of Commerce is in fact lead by a vampire called Rhys, who lives in the tunnels below the city. She sends the party to assassinate him, under the assumption that he is the only one left in Ichiba who can stop her ambitions. The party fight their way into the rooms of the Chamber of Commerce, slaying the director Pickett. In his office they find a secret passage that leads to the lair of the vampire. Rhys and his band of undead give battle in the depths. The vampire is slain.

Returning to Imogen's tower, the party finds it sacked and scorched. They ascend to her room at the top, but are confronted by the demon Kepnasha Deatheater, one of the fearsome minions of the dark lord Usark. He explains that immortality was Imogen's goal, and that the powers of the Maze will allow none to escape, not even in that manner. He tells the party not to attempt to escape the Maze, as they cannot possibly prevail against the odds. With reference to Imogen, he reminds them before vanishing that there are fates worse than dying.

Ichiba city is left a broken shell. The gnolls retreat with their spoils, and without organisation neither the chamber of commerce nor the thieves that prey on it return in great numbers.