= Profit and Loss

This plot line deals with the Chamber of Commerce and it's struggle for power in Ichiba.

The CoC taxes trade and commerce. It is the de facto government of the city. Fronted by it's director WE Pickett, it is in fact secretly headed by the vampire Rhys. Neither the Thieves nor Imogen know this, although the have suspicions of hidden power within the Chamber. It's power stems from it's cash reserves and it's army of mercenaries. It conflicts with the Thieves over their theft, and their harassment of city merchants. It lives in fear that Imogen will mobilise the Gnolls against the trade routes or the city.

A notice board outside the Ichiba COC advertises mercenaries wanted. Tearing off a slip, the party gives it to the stern guardsman at the door of the CoC. They are allowed in to proceed up to the Director, who interviews them and offers to sign them up as mercenaries on a task by task basis.

Part of the COC strategy in Ichiba is to crack down on gnolls in the city, in order to cramp Imogen. The first task that Pickett has for the party is to go to the gnoll merchant Red Ear near the waterfront and collect taxes from him. He presents them with an invoice. Going to Red Ear, the gnoll is angry that the debt collectors have arrived. He lies and claims not to be able to read the invoice. The party tells him the amount owing. He lies again and claims not to have the money. Finally on being threatened with violence, he gives in and vanishes into then rear of his shop, returning with the outstanding taxes. He hurls insults, and will not trade with the party again. Pickett is pleased and rewards the party with gold and a round on his tab at the Adventurer's Arms.

Pickett has more work ready for the party. Robbers have hit an affiliated merchant in the city. He believes that they are still hiding out in the city. The party must locate their safe house and administer justice. As a clue, he offers the fact that some distinctive china plates were taken. Asking around town, the party speaks to the inn keeper Scrymgeour who apologises for having no brandy available and claims that a group of goblins came and drank it all. He is thankful that they left his establishment At least they headed back to the north side. On a hunch, the party search through the derelict houses on the north side of town. They locate the goblins in a room where the floor is littered with broken china. After killing the goblins, they return to Pickett and are rewarded with more gold and another round at the bar.

Pickett now asks the party to travel to the site of the city Hail. Hail was a trading partner, but the caravans stopped coming a year ago and word is that it has been sacked and razed by the forces of the Maze. The party will need to negotiate with either the Gnomes or the Leonals to gain access to the wilderness domains that surround Hail. Leaving Ichiba, the party either reaches Hail through the Leonal castle Danaos and the Stygios Forest, or the Gnome city of Aenen and the peak of Tornado Mountain. Once in Hail they discover nothing more than ruins - it is clear that the city is broken and deserted. Returning to Ichiba, they are rewarded with gold, and another round at the bar.

Pickett praises the party's good work, and has one more quest for them. It is time to hunt down the infamous leader of the guild of thieves - the rascal calling himself Sir Kay. The price on his head is high. The party head back to the streets of Ichiba and track down and attack Kay. He calls for his inner circle of master thieves, who emerge from the shadows and give battle. The fight is quick and bloody, and Kay is slain.

Without Kay to lead them the thieves splinter either succumb one by one or flee from Ichiba. Imogen, faced with a CoC that is free of distractions, leaves Ichiba to pursue her ambitions elsewhere. The rule, and equally importantly the profit, of the CoC is unchallenged in Ichiba.