= The First Realm

The First Realm is, perhaps, the most subtle and dangerous trap that the Maze has in it's arsenal. Offering several large, safe domains, it is a gilded cage that few banished there care to escape. Here the races of the Realm have established their peaceful and prosperous settlements, where most are content to remain rather than brave the terrors of the Maze.

The first realm consists of two rings of domains. On the outside are six large temperate domains. These surround three less hospitable domains - predominantly mountainous. In the center is a large, wild domain that contains the Great Gate to the Second Realm.

Of the outer domains:

* Cosmopolitan human cities with thriving trade dot most of the large outer domains.
* Immortal elves bide their time in white castles in the forests.
* The warm coastlines and island chains of several domains are dotted with Merfolk villages.
* Troll hamlets are scattered in the hills of many domains here, as well as some of the inner domains.
* Atop an isolated plateau, a domed and spired city of Naga has been transported from outside the Maze.
* A small colony of Automata inhabit a shanty town and slowly dwindle as their resources run out.


Of the inner domains:

* Dwarves keep a large city delved deep into the mountains.
* Mirka tribes roam above ground and dwell in villages shallow cave complexes.
* A colony of Salamanders has inhabited a dormant volcano.


In the center of the realm, dire foes lurk in a wild, uninhabited domain. Dark forests and swamps surround a central mountain range of young, jagged peaks. In a cave beneath the highest peak, a guardian beast defends the chamber of the Great Gate, the only way to proceed to the Second Realm.

== Places

Bleak Hills: In winter the Bleak Hills are frosted still and the wilder Mirka tribes cross the gates from the snow-bound mountains to hunt in the pale sunlight. In summer the rains come falling sideways in the east wind and turn the hills into a labyrinth of flash floods and mud slides. Inhabited by few villages and crofters.

The Six Seas: Mariners count six seas in the first Realm: three adjacent to each of the three cities and three sea-only domains. Gates large enough to pass ships through accommodate all the seas.

Janpur: One of the three cities.

Red Hills: Forested hills on the border of inhabited lands.

Briarwood: large forest

White Mountains: Snow clad mountains in the inner domains. Inhabited by Mirka tribes.

Emyn Beowyn: Rugged hills on the borders of civilised lands. Inhabited by Neotroll tribes.

Kilin: One of the three cities.

Naomasa Domain: One of the outer domains.

North Road: Road linking Janpur and Kilin

Red Valley: Secret valley in Naomasa domain.

Emyn Bryn: Rugged hills on the borders of civilised lands. Inhabited by Neotroll tribes and bandits

Bramblewood: large forest

Mount Miska: dormant volcano standing alone amidst the civilised lands

Ponang: One of the three cities. Different domain to Kilin and Janpur.

Menyr: Site of a great temple.

Monastery of the Five Flowers: High in the moutains of Naomasa domain.

Dao River: River running through one of the uncivilised outer domains.

Daningrad: Large city, not counted as one of the three cities because it is landlocked and in a different domain to Kilin and Janpur.

The Spiral: Notorious dungeon.

Tomb of Uatna: Notorious dungeon.

Carpenters Workshop: Notorious dungeon.

Yamashiro Monastery: High in the moutains of the Naomasa domain.

Broken Hills: Hills in Janpur domain.

== People

Argivo: Famous fencing master in Kilin.

Armand: General who defeated the invasion of the creatures of the Maze.

The Prince: Ruler of Kilin domain.

Commission of Justice: An organisation to dedicated to tracking down and eradicating evil in whatever form it reared it's head.

Anacreon: Famous bard.

Estaban: Notorious bandit chief.

Augustin: Renowned druid of the Bramblewood. Deceased before the Year of the Lizard.

Abbot Graves: Leader of the monastery of the Forty. Deceased at the battle of Caradam River.

Sergei the Smith: Renowned blacksmith.

Master Xen Xeng: Master of the Five Flowers.

Bear Tribe: Tribe living along Dao River.

Cyme: Former female gladiator, runs a school in Daningrad.

Shun Oko: Master of Yamashiro Monastery.

Shogun of Naomasa: Ruler of Naomasa domain.

== Events

Invasion of the Maze: Creatures of the Maze invaded in force in the year of the Lizard.

Battle of Gernoed: Defenders of the first Realm united but were defeated on the moors of Gernoed.

Armand's campaign: General Armand rallied the survivors and fought a strategic retreat until he was able to take a stand.

Battle of Caradam River: Armand met and decisively defeated the creatures of the Maze at Caradam River. The first Realm was safe, for now.