= The Maze

No one remembers any more how the various races came to be imprisoned in the Maze. For uncounted generations the Maze has been their jail and their jailer, and few have ever escaped its clutches.

The Maze is formed of many domains, some as large as continents, others as small as houses. Domains are joined by lesser gates, various in appearance but uniform in their function of transporting a traveller across time and space. Domains that are interconnected by easily passable gates make up a Realm; Realms are joined by greater Gates, always perilously guarded, and form the outward path a traveller seeking to escape the Maze must follow.

There are twenty Realms in the Maze. It's origins are uncertain, as is what lies beyond.

Seven dark masters watch over the Maze, tasked with being prison keepers and enforcers of captivity. When mortals come too close to escaping it's confines, they move against them.

== Usark
The first of the dark lords of the Maze is the demon Usark. The first, second and third realms are his. He is also called Usark the Dire, Usark the Proud, and Usark Eyeless. He commands thirty demonic generals, each of them master of a number of legions of the forces of hell.

His generals include

* Imunos
* Kepnasha Deatheater: 7 legions
* Nusor the Torturer: 5 legions
* Saropon the Vile: 6 legions
* Nhapukom Banesoul