= Theology

Various deities are referenced, mostly as flavour.

== Garret
The Grey Wayfarer, He Who Wanderers In Shadows

The ambivalent patron of heroes, adventurers and wayfarers; the cloaked one who stands guard before those who watch their own backs. The bat, the cat and the spider are his creatures; the road and the alleyway his holy places.

== The White Lady
The Shield Maiden, Iron Goddess of Justice and Mercy.

Bearing the spear of Truth in one hand and the shield of Faith in the other, she watches over the just and the downtrodden; patron of soldiers, pilgrims and peasants. Her servants are inclined to be rather humourless, but unlikely to deal falsely with you.

== Nergal
He Who Sows And He Who Reaps, The Eyeless Face

The deathly god of the underworld - a god of emptiness and endings. A desert god, a fire god, a god of unlife.

== Wasud
The Knight of Swords, the Warbrinder, Defender Of The Broken Wall

Patron of gladiators and mercenaries, strife and combat.

== Aello
The Runner, She Who Flies

The messenger goddess, she of the wing and the whirlwind, faster than a ray of sunshine. She carries word on swiftly and surely.

== Beiweh
Mistress Of The Rains, Lady Of The Harvest

The spring goddesses, patrons of sunshine, fertility, rain and love. They of the shining face bring growth and health on all creatures.